# Generated by Django 3.1 on 2020-09-21 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='createionDate',
            new_name='creationDate',
        ),
    ]
