# Generated by Django 3.1 on 2020-09-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200924_0500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listingId',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='listingId',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='listingID',
            new_name='listing',
        ),
    ]
