# Generated by Django 3.1 on 2020-10-05 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200929_0540'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('listing', 'user')},
        ),
    ]
