# Generated by Django 3.1 on 2020-09-21 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200921_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='commentDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
