# Generated by Django 3.1 on 2020-09-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200921_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='highestBid',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
