# Generated by Django 3.1.1 on 2020-10-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201005_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_title',
            field=models.TextField(default='Customer Review', max_length=100),
        ),
    ]
