# Generated by Django 3.1 on 2020-09-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200921_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='name',
            field=models.CharField(default='Item', max_length=512),
        ),
    ]
