# Generated by Django 3.1 on 2020-09-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default='Item Description', max_length=1500),
        ),
    ]
