# Generated by Django 3.1 on 2020-09-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='item_image',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
