# Generated by Django 3.1 on 2020-09-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200923_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='startingBid',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
